package com.invoice.approval.repo;

import java.util.Date;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.invoice.approval.entity.GstInvoiceHdrVO;

public interface GstInvoiceHdrRepo extends JpaRepository<GstInvoiceHdrVO, Long> {

	
	@Query(nativeQuery = true,value = "select gst_invoicehdrid,a.branchcode,finyr,docid,docdt,Partyname,partycode,outstanding,totinvamtlc,"
			+ "b.creditdays,b.creditlimit,slabremarks,exceeddays,eligislab,unapproveamt,approve1,approve2,approve3,approve1name,approve1on,osbeyond,excesscredit,category,controllingoffice from gst_invoicehdr a,mg_partyhdr b \r\n"
			+ "where invproceed = 'F' and approve1 = 'F' and a.partycode = b.party_code and approve1name is null"
			+ " AND eligislab = 1 AND a.branchcode in (select branchcode from vg_userbranch where (userName =?1 or 'admin'=?1 ))  order by a.createdon desc")
	Set<Object[]> getPendingDetailsApprove1slab1(String userName);

	@Query(value = "select a from GstInvoiceHdrVO a where a.gstInvoiceHdrId=?1")
	GstInvoiceHdrVO findByGstInvoiceHdrId(Long id);
	
	@Query(nativeQuery = true,value = "select gst_invoicehdrid,a.branchcode,finyr,docid,docdt,Partyname,partycode,outstanding,totinvamtlc,b.creditdays,b.creditlimit,slabremarks,decode(exceeddays,'91','90P',exceeddays)exceeddays,eligislab,unapproveamt,approve1,approve1name,approve1on,approve2,approve2name,approve2on,approve3,approve3name,approve3on,osbeyond,excesscredit,category,controllingoffice, case when lower(salesperson) like 'uwl%' then 'Mr./Ms. '||initcap(salespersonname) else initcap(salespersonname) end salespersonname \r\n"
			+ "from gst_invoicehdr a,mg_partyhdr b \r\n"
			+ "where invproceed = 'F' and eligislab = 1 and approve1 = 'T' and a.partycode = b.party_code and  approve2='F' and approve2name is null and a.branchcode in (select branchcode from vg_userbranch where (userName =?1 or 'admin'=?1 )) order by a.createdon desc")
	Set<Object[]> getPendingDetailsApprove2slab1(String userName);
	
	@Query(nativeQuery = true,value = "select gst_invoicehdrid,a.branchcode,finyr,docid,docdt,Partyname,partycode,outstanding,totinvamtlc,b.creditdays,b.creditlimit,slabremarks,decode(exceeddays,'91','90P',exceeddays)exceeddays,eligislab,unapproveamt,approve1,approve1name,approve1on,approve2,approve2name,approve2on,approve3,approve3name,approve3on,osbeyond,excesscredit,category,controllingoffice,case when lower(salesperson) like 'uwl%' then 'Mr./Ms. '||initcap(salespersonname) else initcap(salespersonname) end salespersonname \r\n"
			+ "from gst_invoicehdr a,mg_partyhdr b \r\n"
			+ "where invproceed = 'F' and eligislab in (2,3) and approve1 = 'F' and a.partycode = b.party_code and approve1name is null and a.branchcode in (select branchcode from vg_userbranch where userName =?1) order by a.createdon desc")
	Set<Object[]> getPendingDetailsApprove1slab2(String userName);
	
@Query(nativeQuery = true,value = "select mg_partyhdrid,b.party_name partyName,b.party_code partyCode,b.creditlimit,b.creditdays,category,case when lower(salesperson) like 'uwl%' then 'Mr./Ms. '||initcap(salespersonname) else initcap(salespersonname) end salespersonname, controllingoffice \r\n"
			+ "from mg_partyhdr b \r\n"
			+ "where gstflag = 1 and active = 'T'  and ccod = 'Credit'  order by party_name ")
	Set<Object[]> getAllCreditParties();
	
	
	@Query(nativeQuery = true,value = "select a.docid,a.docdt,partyname,partycode,b.docid vchno,b.docdate vchdt,totinvamtlc from gst_invoicehdr a,accountshdr b \r\n"
			+ "where a.docid = b.refno and a.branchcode in ( select branchcode from vg_userbranch where username = ?1) "
			+ " and a.branchcode = (select distinct branchcode from vg_userbranch where branchname = ?2 and username = ?1 )  \r\n"
			+ "order by 1 ")
	Set<Object[]> getInvoices(String userName,String branchName);
	
	
	@Query(nativeQuery = true,value = "select gst_invoicehdrid,a.branchcode,finyr,docid,docdt,Partyname,partycode,outstanding,totinvamtlc,b.creditdays,b.creditlimit,unapproveamt,approve1,approve2,approve3,approve1name,approve1on,approve2name,approve2on,approve3on,osbeyond,excesscredit,category,controllingoffice,case when lower(salesperson) like 'uwl%' then 'Mr./Ms. '||initcap(salespersonname) else initcap(salespersonname) end salespersonname from gst_invoicehdr a,mg_partyhdr b \r\n"
			+ "where  a.partycode = b.party_code and approve1 = 'T' and approve1name is not null and ( approve1name=?1 or 'admin'=?1 ) "
			 + " and eligislab = 1 AND a.branchcode in (select branchcode from vg_userbranch where userName =?1) order by a.createdon desc")
	Set<Object[]> getInvDetailsApprove1(String userName);
	
	@Query(nativeQuery = true,value = "select gst_invoicehdrid,a.branchcode,finyr,docid,docdt,Partyname,partycode,outstanding,totinvamtlc,b.creditdays,b.creditlimit,unapproveamt,approve1,approve2,approve3,approve1name,approve1on,approve2name,approve2on,approve3on,osbeyond,excesscredit,category,controllingoffice,case when lower(salesperson) like 'uwl%' then 'Mr./Ms. '||initcap(salespersonname) else initcap(salespersonname) end salespersonname from gst_invoicehdr a,mg_partyhdr b \r\n"
			+ "where invproceed = 'T' and a.partycode = b.party_code and approve2 = 'T' and approve2name is not null and ( approve2name=?1 or 'admin'=?1 ) \r\n"
			+ " and eligislab = 1 AND a.branchcode in (select branchcode from vg_userbranch where userName =?1)  order by a.createdon desc")
	Set<Object[]> getInvDetailsApprove2(String userName);
	
	
	@Query(nativeQuery = true,value = "select gst_invoicehdrid,a.branchcode,finyr,docid,docdt,Partyname,partycode,outstanding,totinvamtlc,b.creditdays,b.creditlimit,unapproveamt,approve1,approve2,approve3,approve1name,approve1on,approve2name,approve2on,approve3on,osbeyond,excesscredit,category,controllingoffice,case when lower(salesperson) like 'uwl%' then 'Mr./Ms. '||initcap(salespersonname) else initcap(salespersonname) end salespersonname from gst_invoicehdr a,mg_partyhdr b \r\n"
			+ "where approve1 = 'T' and a.partycode = b.party_code and approve1name is not null  and (approve1name=?1 or 'admin'=?1 ) \r\n"
			+ " and eligislab in (2,3) AND a.branchcode in (select branchcode from vg_userbranch where userName =?1)  order by a.createdon desc")
	Set<Object[]> getInvDetailsApprove3(String userName);
	
	
	@Query(nativeQuery = true,value = "select branchname from vg_userbranch where username = ?1 order by 1")
	Set<Object[]> getUserBranch(String userName);
	

	@Query(nativeQuery = true,value = "select subledgercode,subledgername from mg_subledger a, mg_account b \r\n"
			+ " where \r\n"
			+ " a.cancel='F'  and a.controlaccount=b.mg_accountid \r\n"
			+ " and b.acatcode in('r','p') and a.gstflag <> 0 and subledgername is not null\r\n"
			+ " union\r\n"
			+ "select 'ALL' subledgercode,'ALL' subledgername from dual  \r\n"
			+ " order by 2 ")
	Set<Object[]> getAllAPParties();
	
	
	@Query(nativeQuery = true,value = "SELECT jobbranch,SUM (income) income, SUM (expense) expense, SUM (profit) Profit , SUM \r\n"
			+ "            (branchprofit) branchprofit\r\n"
			+ "            , SUM (cbprofit) cbprofit, SUM (ibprofit) ibprofit, SUM (interbprofit) interbprofit, 1 sno\r\n"
			+ "            FROM (\r\n"
			+ "            Select code, jobbranch,  SUM (income) income, SUM (expense) expense, SUM (profit) profit\r\n"
			+ "            , SUM (branchprofit) branchprofit, SUM (cbprofit) cbprofit, SUM (ibprofit) ibprofit, SUM (interbprofit) \r\n"
			+ "            interbprofit FROM mvw_abmis WHERE  (branchname = ?1 or 'ALL' = ?1) AND status = ?2  \r\n"
			+ "            And code = 1  AND case when misc=0 then to_date(closeddt) else to_date(vchdt) end BETWEEN to_date(?3) AND \r\n"
			+ "             to_date(?4)  \r\n"
			+ "            GROUP BY code, jobbranch\r\n"
			+ "            union\r\n"
			+ "            Select code, cbranch jobbranch,   SUM (income) income, SUM (expense) expense, SUM (profit) profit\r\n"
			+ "            , SUM (branchprofit) branchprofit, SUM (cbprofit) cbprofit, SUM (ibprofit) ibprofit, SUM (interbprofit) \r\n"
			+ "            interbprofit FROM mvw_abmis WHERE  (branchname = ?1 or 'ALL' = ?1) AND status = ?2  \r\n"
			+ "            And code = 2  AND case when misc=0 then to_date(closeddt) else to_date(vchdt) end BETWEEN to_date( ?3) AND \r\n"
			+ "             to_date(?4)  \r\n"
			+ "            GROUP BY code, jobbranch,cbranch\r\n"
			+ "            ) group by jobbranch \r\n"
			+ "            union\r\n"
			+ "            SELECT 'GRAND TOTAL' jobbranch,SUM (income) income, SUM (expense) expense, SUM (profit) Profit , SUM \r\n"
			+ "            (branchprofit) branchprofit\r\n"
			+ "            , SUM (cbprofit) cbprofit, SUM (ibprofit) ibprofit, SUM (interbprofit) interbprofit, 2 sno\r\n"
			+ "            FROM (\r\n"
			+ "            Select code, jobbranch,  SUM (income) income, SUM (expense) expense, SUM (profit) profit\r\n"
			+ "            , SUM (branchprofit) branchprofit, SUM (cbprofit) cbprofit, SUM (ibprofit) ibprofit, SUM (interbprofit) \r\n"
			+ "            interbprofit FROM mvw_abmis WHERE  (branchname = ?1 or 'ALL' = ?1) AND status = ?2  \r\n"
			+ "            And code = 1  AND case when misc=0 then to_date(closeddt) else to_date(vchdt) end BETWEEN to_date(?3) AND \r\n"
			+ "             to_date(?4)  \r\n"
			+ "            GROUP BY code, jobbranch\r\n"
			+ "            union\r\n"
			+ "            Select code, cbranch jobbranch,   SUM (income) income, SUM (expense) expense, SUM (profit) profit\r\n"
			+ "            , SUM (branchprofit) branchprofit, SUM (cbprofit) cbprofit, SUM (ibprofit) ibprofit, SUM (interbprofit) \r\n"
			+ "            interbprofit FROM mvw_abmis WHERE  (branchname = ?1 or 'ALL' = ?1) AND status = ?2  \r\n"
			+ "            And code = 2  AND case when misc=0 then to_date(closeddt) else to_date(vchdt) end BETWEEN to_date( ?3) AND \r\n"
			+ "             to_date(?4)  \r\n"
			+ "            GROUP BY code, jobbranch,cbranch\r\n"
			+ "            ) order by 9,1"
			+ "")
	Set<Object[]> getMIS(String branchName,String status,String fromDate,String toDate);
	

	
	
	@Query(nativeQuery = true,value = " SELECT arapdetailsid,\r\n"
			+ "         doctypecode,\r\n"
			+ "         branchname,\r\n"
			+ "         subledgercode,\r\n"
			+ "         subledgername,\r\n"
			+ "         partytype,\r\n"
			+ "         cbranch,\r\n"
			+ "         salespersonname,\r\n"
			+ "         subledgerdivision,\r\n"
			+ "         currency,\r\n"
			+ "         docid,\r\n"
			+ "         docdate,\r\n"
			+ "         supprefno,\r\n"
			+ "         supprefdate,\r\n"
			+ "         duedate,\r\n"
			+ "         refno,\r\n"
			+ "         refdate,\r\n"
			+ "         mno,\r\n"
			+ "         hno,\r\n"
			+ "         DECODE ('Base',  'Base', bamount,  'Native', namount,  amount) amount,\r\n"
			+ "         DECODE ('Base',\r\n"
			+ "                 'Base', boutstanding,\r\n"
			+ "                 'Native', noutstanding,\r\n"
			+ "                 outstanding)\r\n"
			+ "            outstanding,\r\n"
			+ "         DECODE ('Base',  'Base', btotaldue,  'Native', ntotaldue,  totaldue)\r\n"
			+ "            totaldue,\r\n"
			+ "         DECODE ('Base',\r\n"
			+ "                 'Base', bunadjusted,\r\n"
			+ "                 'Native', nunadjusted,\r\n"
			+ "                 unadjusted)\r\n"
			+ "            unadjusted,\r\n"
			+ "         ddays,\r\n"
			+ "         DECODE ('Base',  'Base', bmslab1,  'Native', nmslab1,  mslab1) mslab1,\r\n"
			+ "         DECODE ('Base',  'Base', bmslab2,  'Native', nmslab2,  mslab2) mslab2,\r\n"
			+ "         DECODE ('Base',  'Base', bmslab3,  'Native', nmslab3,  mslab3) mslab3,\r\n"
			+ "         DECODE ('Base',  'Base', bmslab4,  'Native', nmslab4,  mslab4) mslab4,\r\n"
			+ "         DECODE ('Base',  'Base', bmslab5,  'Native', nmslab5,  mslab5) mslab5,\r\n"
			+ "         DECODE ('Base',  'Base', bmslab6,  'Native', nmslab6,  mslab6) mslab6,\r\n"
			+ "         DECODE ('Base',  'Base', bmslab7,  'Native', nmslab7,  mslab7) mslab7,\r\n"
			+ "         transid,whrefno,product,party_type\r\n"
			+ "    FROM (  SELECT a.arapdetailsid,\r\n"
			+ "                   a.doctypecode,\r\n"
			+ "                   br.branchname,\r\n"
			+ "                   m.subledgercode,\r\n"
			+ "                   m.subledgername,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN  (m.subledgercode LIKE 'G%' or m.subledgercode LIKE 'I%') THEN 'GST Party'\r\n"
			+ "                      ELSE 'ST Party'\r\n"
			+ "                   END\r\n"
			+ "                      Partytype,\r\n"
			+ "                   p.controllingoffice cbranch,\r\n"
			+ "                   p.salespersonname,\r\n"
			+ "                   a.subledgerdivision,\r\n"
			+ "                   DECODE ('Base',\r\n"
			+ "                           'Base', (SELECT currency FROM control),\r\n"
			+ "                           'Native', m.currency,\r\n"
			+ "                           a.currency)\r\n"
			+ "                      currency,\r\n"
			+ "                   a.docid ,\r\n"
			+ "                   a.docdate,\r\n"
			+ "                   a.supprefno,\r\n"
			+ "                   a.supprefdate,\r\n"
			+ "                   a.duedate,\r\n"
			+ "                   a.refno,\r\n"
			+ "                   a.refdate,\r\n"
			+ "                   a.mno,\r\n"
			+ "                   a.hno,\r\n"
			+ "                   a.amount AS amount,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                            OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                      THEN\r\n"
			+ "                         0\r\n"
			+ "                      ELSE\r\n"
			+ "                         a.amount + NVL (SUM (NVL (r.amount, 0)), 0)\r\n"
			+ "                   END\r\n"
			+ "                      AS outstanding,\r\n"
			+ "                   a.amount + NVL (SUM (NVL (r.amount, 0)), 0) AS totaldue,\r\n"
			+ "                   a.bamount AS bamount,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                            OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                      THEN\r\n"
			+ "                         0\r\n"
			+ "                      ELSE\r\n"
			+ "                         a.bamount + NVL (SUM (NVL (r.bamount, 0)), 0)\r\n"
			+ "                   END\r\n"
			+ "                      AS boutstanding,\r\n"
			+ "                   a.bamount + NVL (SUM (NVL (r.bamount, 0)), 0) AS btotaldue,\r\n"
			+ "                   a.namount AS namount,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                            OR (a.refno LIKE '%CREC%' OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                      THEN\r\n"
			+ "                         0\r\n"
			+ "                      ELSE\r\n"
			+ "                         a.namount + NVL (SUM (NVL (r.namount, 0)), 0)\r\n"
			+ "                   END\r\n"
			+ "                      AS noutstanding,\r\n"
			+ "                   a.namount + NVL (SUM (NVL (r.namount, 0)), 0) AS ntotaldue,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN     (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                    OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                           AND a.amount + NVL (SUM (NVL (r.amount, 0)), 0) <> 0\r\n"
			+ "                      THEN\r\n"
			+ "                         a.amount + NVL (SUM (NVL (r.amount, 0)), 0)\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS unadjusted,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN     (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                    OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                           AND a.bamount + NVL (SUM (NVL (r.bamount, 0)), 0) <> 0\r\n"
			+ "                      THEN\r\n"
			+ "                         a.bamount + NVL (SUM (NVL (r.bamount, 0)), 0)\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bunadjusted,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN     (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                    OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                           AND a.namount + NVL (SUM (NVL (r.namount, 0)), 0) <> 0\r\n"
			+ "                      THEN\r\n"
			+ "                         a.namount + NVL (SUM (NVL (r.namount, 0)), 0)\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nunadjusted,\r\n"
			+ "                     TO_DATE (?5)\r\n"
			+ "                   - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)\r\n"
			+ "                      AS ddays,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) <\r\n"
			+ "                              ?6\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + NVL (SUM (NVL (r.amount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab1,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) <\r\n"
			+ "                              ?6\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY %'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.bamount + NVL (SUM (NVL (r.bamount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab1,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) <\r\n"
			+ "                              ?6\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.namount + NVL (SUM (NVL (r.namount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab1,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) BETWEEN ?6\r\n"
			+ "                                                                                     AND (  ?7\r\n"
			+ "                                                                                          - 1)\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + NVL (SUM (NVL (r.amount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab2,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) BETWEEN ?6\r\n"
			+ "                                                                                     AND (  ?7\r\n"
			+ "                                                                                          - 1)\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.bamount + NVL (SUM (NVL (r.bamount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab2,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) BETWEEN ?6\r\n"
			+ "                                                                                     AND (  ?7\r\n"
			+ "                                                                                          - 1)\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.namount + NVL (SUM (NVL (r.namount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab2,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) BETWEEN ?7\r\n"
			+ "                                                                                     AND (  ?8\r\n"
			+ "                                                                                          - 1)\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + NVL (SUM (NVL (r.amount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab3,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) BETWEEN ?7\r\n"
			+ "                                                                                     AND (  ?8\r\n"
			+ "                                                                                          - 1)\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.bamount + NVL (SUM (NVL (r.bamount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab3,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) BETWEEN ?7\r\n"
			+ "                                                                                     AND (  ?8\r\n"
			+ "                                                                                          - 1)\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.namount + NVL (SUM (NVL (r.namount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab3,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) BETWEEN ?8\r\n"
			+ "                                                                                     AND (  ?9\r\n"
			+ "                                                                                          - 1)\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + NVL (SUM (NVL (r.amount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab4,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) BETWEEN ?8\r\n"
			+ "                                                                                     AND (  ?9\r\n"
			+ "                                                                                          - 1)\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.bamount + NVL (SUM (NVL (r.bamount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab4,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) BETWEEN ?8\r\n"
			+ "                                                                                     AND (  ?9\r\n"
			+ "                                                                                          - 1)\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.namount + NVL (SUM (NVL (r.namount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab4,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) BETWEEN ?9\r\n"
			+ "                                                                                     AND (  ?10\r\n"
			+ "                                                                                          - 1)\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + NVL (SUM (NVL (r.amount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab5,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) BETWEEN ?9\r\n"
			+ "                                                                                     AND (  ?10\r\n"
			+ "                                                                                          - 1)\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.bamount + NVL (SUM (NVL (r.bamount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab5,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) BETWEEN ?9\r\n"
			+ "                                                                                     AND (  ?10\r\n"
			+ "                                                                                          - 1)\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.namount + NVL (SUM (NVL (r.namount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab5,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) BETWEEN ?10\r\n"
			+ "                                                                                     AND (  ?11\r\n"
			+ "                                                                                          - 1)\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + NVL (SUM (NVL (r.amount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab6,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) BETWEEN ?10\r\n"
			+ "                                                                                     AND (  ?11\r\n"
			+ "                                                                                          - 1)\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.bamount + NVL (SUM (NVL (r.bamount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab6,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) BETWEEN ?10\r\n"
			+ "                                                                                     AND (  ?11\r\n"
			+ "                                                                                          - 1)\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.namount + NVL (SUM (NVL (r.namount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab6,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) >=\r\n"
			+ "                              ?11\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.amount + NVL (SUM (NVL (r.amount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS mslab7,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) >=\r\n"
			+ "                              ?11\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.bamount + NVL (SUM (NVL (r.bamount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS bmslab7,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN (  TO_DATE (?5)\r\n"
			+ "                            - DECODE ('DocDate', 'Due_Date', a.duedate, a.docdate)) >=\r\n"
			+ "                              ?11\r\n"
			+ "                      THEN\r\n"
			+ "                         CASE\r\n"
			+ "                            WHEN (   a.doctypecode IN ('RC', 'PA')\r\n"
			+ "                                  OR (   a.refno LIKE '%CREC%'\r\n"
			+ "                                      OR a.refno LIKE '%CPAY%'))\r\n"
			+ "                            THEN\r\n"
			+ "                               0\r\n"
			+ "                            ELSE\r\n"
			+ "                               a.namount + NVL (SUM (NVL (r.namount, 0)), 0)\r\n"
			+ "                         END\r\n"
			+ "                      ELSE\r\n"
			+ "                         0\r\n"
			+ "                   END\r\n"
			+ "                      AS nmslab7,\r\n"
			+ "                   't' || TRIM (SUBSTR (a.mapname, 1, 5)) AS transid,w.refno whrefno,a.product,p.party_type\r\n"
			+ "              FROM arapdetails a,  \r\n"
			+ "                   arapadjustments r,\r\n"
			+ "                   mg_subledger m,\r\n"
			+ "                   mg_account b,\r\n"
			+ "                   mg_branchhdr br,\r\n"
			+ "                   mg_partyhdr p,\r\n"
			+ "                   wh_salesvoucherhdr w\r\n"
			+ "             WHERE     a.subledgercode = r.subledgercode(+)\r\n"
			+ "                   AND a.docid = r.docid(+)\r\n"
			+ "                   AND a.subledgercode = m.subledgercode\r\n"
			+ "                   AND m.subledgercode = p.party_code\r\n"
			+ "                   AND m.controlaccount = b.mg_accountid\r\n"
			+ "                   AND a.refno = w.docid(+)\r\n"
			+ "                   AND a.branch = br.mg_branchhdrid\r\n"
			+ "                   AND a.docdate <= ?5\r\n"
			+ "                   AND r.docdate(+) <= ?5\r\n"
			+ "                   AND a.CANCEL = 'F'\r\n"
			+ "                   AND r.CANCEL(+) = 'F'\r\n"
			+ "                    and a.sysoffset='0'\r\n"
			+ "                    and p.rpo = 'P'\r\n"
			+ "                   AND b.acatcode = SUBSTR (LOWER ('Payables'), 1, 1)\r\n"
			+ "                   AND m.subledgertype NOT IN ('PARTNER', 'INTERCOMPANY','FX')\r\n"
			+ "                   And P.PARTY_TYPE <>'IB'\r\n"
			+ "                     AND (   LOWER (TRIM (m.subledgername)) LIKE\r\n"
			+ "                              LOWER ('%' || TRIM (?1) || '%')\r\n"
			+ "                        OR LOWER (TRIM (?1)) = 'all')\r\n"
			+ "                         AND  (case when (br.bdiv) in \r\n"
			+ "('FF','CC') then 'FF' else 'WH' end = ?2 or 'ALL' = upper( ?2))\r\n"
			+ "  and (branchname = decode( ?3, 'Branch',?4) or 'ALL' = decode( ?3,'Pan India','ALL'))\r\n"
			+ "          GROUP BY a.arapdetailsid,\r\n"
			+ "                   br.branchname,\r\n"
			+ "                   m.subledgercode,\r\n"
			+ "                   m.subledgername,w.refno,\r\n"
			+ "                   CASE\r\n"
			+ "                      WHEN  (m.subledgercode LIKE 'G%' or m.subledgercode LIKE 'I%') THEN 'GST Party'\r\n"
			+ "                      ELSE 'ST Party'\r\n"
			+ "                   END,\r\n"
			+ "                   p.controllingoffice,\r\n"
			+ "                   p.salespersonname,p.party_type,\r\n"
			+ "                   a.subledgerdivision,\r\n"
			+ "                   a.currency,\r\n"
			+ "                   m.currency,\r\n"
			+ "                   a.docid,\r\n"
			+ "                   a.docdate,\r\n"
			+ "                   a.supprefno,\r\n"
			+ "                   a.supprefdate,\r\n"
			+ "                   a.creditdays,\r\n"
			+ "                   a.amount,\r\n"
			+ "                   a.bamount,\r\n"
			+ "                   a.namount,\r\n"
			+ "                   a.refno,\r\n"
			+ "                   a.refdate,\r\n"
			+ "                   a.mno,\r\n"
			+ "                   a.hno,\r\n"
			+ "                   a.duedate,\r\n"
			+ "                   a.mapname,\r\n"
			+ "                   a.doctypecode,a.product\r\n"
			+ "            HAVING (a.amount + NVL (SUM (NVL (r.amount, 0)), 0)) != 0)\r\n"
			+ "ORDER BY branchname,party_type,subledgername,\r\n"
			+ "         partytype,\r\n"
			+ "         docdate,\r\n"
			+ "         currency,\r\n"
			+ "         docid\r\n"
			+ "")
	Set<Object[]> getAPAgeingInternal(String sbcode,String div,String ptype,String pbranchname,String asondt,String slab1,String slab2,String slab3,String slab4,String slab5,String slab6);
}
